### ISSUE TITLE
`protoc-gen-swift`of v3.1.26 splits `no version information available` error

### ISSUE THREAD

**Issue by xissy** [rvolosatovs/docker-protobuf#57] opened 2020-06-28 03:36 UTC
#### Summary
`protoc-gen-swift`of v3.1.26 splits `no version information available` error messages. 
...

#### Steps to Reproduce
1. $ docker run --rm -it --name protoc --entrypoint /bin/sh thethingsindustries/protoc:3.1.26
2. $ protoc-gen-swift

#### What do you see now?
```
/ # protoc-gen-swift
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicuucswift.so.61)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicuucswift.so.61)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicui18nswift.so.61)
protoc-gen-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicui18nswift.so.61)
```

#### What do you want to see instead?
No error messages.

#### Environment
MacOS 10.15.5, Docker 2.3.0.3

**Comment by rvolosatovs** [comment] 2020-07-10 17:33
I suppose this is caused by https://github.com/TheThingsIndustries/docker-protobuf/pull/54
Is this purely cosmetic issue, or is the plugin itself broken as well?

**Comment by Min3953** [comment] 2020-08-06 03:47
@rvolosatovs any update? same thing to me.

**Comment by rvolosatovs** [comment] 2020-08-07 14:41
@tenpaiyomi do you have any clue what could be going wrong?

**Comment by tenpaiyomi** [comment] 2020-08-07 17:28
Generally the noted shared objects are looking for version information from the requested file.  In this case, seems like the Swift libs are trying to get version information from the `libstdc++.so` lib.  Normally this is just a superficial thing and won't actually cause any errors, but can be resolved.

First off, is it possible to get the output of `ldconfig -p` from within the running container?

**Comment by rvolosatovs** [comment] 2021-04-16 20:07
Probably closed by https://github.com/TheThingsIndustries/docker-protobuf/pull/76
Please reopen if this is still relevant

**Closed as completed** 2021-04-16 20:07 UTC
Labels: bug, help wanted
